#!/bin/bash

PROJECT_DIR=$(git rev-parse --show-toplevel)

pushd "$PROJECT_DIR"
npm run fix
popd

while read -r file;
do

if [[ $file = *.ts ]];
then
git add "$PROJECT_DIR/$(echo -e $file)"
fi

if [[ $file = *.tsx ]];
then
git add "$PROJECT_DIR/$(echo -e $file)"
fi

if [[ $file = *.json ]];
then
git add "$PROJECT_DIR/$(echo -e $file)"
fi

if [[ $file = *.md ]];
then
git add "$PROJECT_DIR/$(echo -e $file)"
fi

done < <(git diff --cached --name-only --diff-filter=ACM)
